<template>
	<footer
		class="mt-16 border-t border-gray-200 pt-8 text-center text-sm text-gray-500 dark:border-gray-700 dark:text-gray-400">
		<div class="mb-4 flex items-center justify-center gap-4">
			<a
				href="https://weatherapi.com"
				target="_blank"
				rel="noopener noreferrer"
				class="transition-colors hover:text-blue-600 dark:hover:text-blue-400">
				Weather Data by WeatherAPI
			</a>
			<span>|</span>
			<a
				href="https://github.com"
				target="_blank"
				rel="noopener noreferrer"
				class="transition-colors hover:text-blue-600 dark:hover:text-blue-400">
				Source Code
			</a>
		</div>
		<p>© {{ new Date().getFullYear() }} Weatherspeare. All rights reserved.</p>
		<p class="mt-2 text-xs">
			Shakespearean monologues generated by AI. For entertainment purposes only.
		</p>
	</footer>
</template>

<script setup lang="ts"></script>
